# =============================================================================
#  Daily Update
# =============================================================================
# This workflow runs daily to update the hosts file.
#
# NOTE:
# You need to set the `PERSONAL_ACCESS_TOKEN` environment variable in the repo's
#     [Settings]-[Secrets]-[Actions secrets]
# To generate a new token go to:
#     https://github.com/settings/tokens
#     * You need add the "repo" scope to the token but no more.
# =============================================================================
name: Daily Update

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 18900 UTC (JST: AM 04:00 @ Japan time)
    - cron: '0 19 * * *'

jobs:
  daily_update:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update hosts file (API resource heavy)
        run: |
          set -eu
          docker compose run update

      - name: Create Pull Request on Change
        uses: peter-evans/create-pull-request@v7
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
